---
- hosts: web
  become: true

  tasks:

    - name: Install Docker
      yum:
        name: docker
        state: present

    - name: Start Docker
      service:
        name: docker
        state: started
        enabled: true

    - name: Install Git
      yum:
        name: git
        state: present

    - name: Install Docker Compose
      get_url:
        url: https://github.com/docker/compose/releases/download/v2.24.6/docker-compose-linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: '0755'

    - name: Create app directory
      file:
        path: /home/ec2-user/app
        state: directory

    - name: Copy app files
      copy:
        src: ../app/
        dest: /home/ec2-user/app/

    - name: Run docker compose
      command: docker compose up -d
      args:
        chdir: /home/ec2-user/app